name: Back merge hotfix to staging
on:
  push:
    branches: [master]
jobs:
  backmerge-master:
    runs-on: ubuntu-22.04
    steps:
      - name: Set Git config
        run: |
          git config --global user.email "test@imptrx.com"
          git config --global user.name "SA Test"

      - name: Checkout staging
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.IMPTR_PAT }}
          repository: imptrx/Angular-Personal-Site
          ref: staging

      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.IMPTR_PAT }}
      - name: Merge master back to staging
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff origin/master -m "Auto-merge master back to staging"

      - name: Pushing to the protected branch 'staging'
        uses: CasperWA/push-protected@6b25de805895da731062c43da647425fbb383128 #v2.14
        with:
          token: ${{ secrets.IMPTR_PAT }}
          branch: staging



