name: Back merge hotfix to staging
on:
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  backmerge-master:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git config
        run: |
          git config --global user.email "test@imptrx.com"
          git config --global user.name "SA Test"

      - name: Checkout staging
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COL_PAT }}
          repository: imptrx/Angular-Personal-Site
          ref: staging

      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.COL_PAT }}
      - name: Merge master back to staging
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff origin/master -m "Auto-merge master back to staging"

      - name: Pushing to the protected branch 'staging'
        uses: CasperWA/push-protected@6b25de805895da731062c43da647425fbb383128 #v2.14
        with:
          token: ${{ secrets.COL_PAT }}
          branch: staging


