name: Dummy Status Check

on:
  pull_request:
    branches:
      - staging
      - master
  push:
    branches: [master]

jobs:
  dummy-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Wait for 5 minutes
        run: |
          echo "Waiting for 5 minutes..."
          sleep 300
      - name: Run dummy status check
        run: |
          echo "This is a dummy status check."
          echo "Everything is okay!"
          echo "No more admin access check."
